# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-25 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text=b"Annotaion number of the verse's word", max_length=5)),
                ('phrase', models.CharField(help_text=b'The words that are annotated', max_length=60)),
                ('annotation', models.TextField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('writer', models.CharField(max_length=150)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bible.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('original_text', models.CharField(help_text=b'Ancient Greek script', max_length=1000)),
                ('greek_translation', models.CharField(help_text=b'Modern Greek translation', max_length=1000, verbose_name=b'Translation')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bible.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bible.Verse'),
        ),
    ]
