# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-29 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text=b"Annotation number of the verse's word", max_length=5)),
                ('phrase', models.CharField(help_text=b'The words that are annotated', max_length=60)),
                ('annotation', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('writer', models.CharField(max_length=160)),
                ('image', models.FileField(default=b'/default.jpg', upload_to=b'')),
                ('abstract_trempelas', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('abstract_trempelas', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bible.Book')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Annotation', verbose_name=b'Annotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'db_table': 'favorite_annotation',
            },
        ),
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book', verbose_name=b'Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'db_table': 'favorite_book',
            },
        ),
        migrations.CreateModel(
            name='FavoriteChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Chapter', verbose_name=b'Chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'db_table': 'favorite_chapter',
            },
        ),
        migrations.CreateModel(
            name='FavoriteVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'favorite_verse',
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('original_text', models.TextField(help_text=b'Ancient Greek script', max_length=1000)),
                ('greek_translation', models.TextField(help_text=b'Modern Greek translation', max_length=1000, verbose_name=b'Translation')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bible.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='favoriteverse',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Verse', verbose_name=b'Verse'),
        ),
        migrations.AddField(
            model_name='favoriteverse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='verse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bible.Verse'),
        ),
    ]
