# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-16 17:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'favorite_book',
            },
        ),
        migrations.CreateModel(
            name='FavoriteChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'favorite_chapter',
            },
        ),
        migrations.CreateModel(
            name='FavoriteVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'favorite_verse',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='abstract_trempelas',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='abstract_trempelas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='annotation',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='number',
            field=models.CharField(help_text=b"Annotation number of the verse's word", max_length=5),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(default=b'/default.jpg', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verse',
            name='greek_translation',
            field=models.TextField(help_text=b'Modern Greek translation', max_length=1000, verbose_name=b'Translation'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verse',
            name='original_text',
            field=models.TextField(help_text=b'Ancient Greek script', max_length=1000),
        ),
        migrations.AddField(
            model_name='favoriteverse',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Verse', verbose_name=b'Verse'),
        ),
        migrations.AddField(
            model_name='favoriteverse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AddField(
            model_name='favoritechapter',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Chapter', verbose_name=b'Chapter'),
        ),
        migrations.AddField(
            model_name='favoritechapter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book', verbose_name=b'Book'),
        ),
        migrations.AddField(
            model_name='favoritebook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
