# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(default=b'/default.jpg', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
