# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-05-29 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteannotation',
            name='user',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='obj',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='bible.Book', verbose_name=b'Book'),
        ),
        migrations.AlterField(
            model_name='favoritebook',
            name='user',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AlterField(
            model_name='favoritechapter',
            name='user',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
        migrations.AlterField(
            model_name='favoriteverse',
            name='user',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User'),
        ),
    ]
