# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-06 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_auto_20180126_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verse',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
