# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-11 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_auto_20180206_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='number',
            field=models.CharField(help_text=b"Annotation number of the verse's word", max_length=5),
        ),
        migrations.AlterField(
            model_name='verse',
            name='greek_translation',
            field=models.TextField(help_text=b'Modern Greek translation', max_length=1000, verbose_name=b'Translation'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='original_text',
            field=models.TextField(help_text=b'Ancient Greek script', max_length=1000),
        ),
    ]
