# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_auto_20180211_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='annotation',
            field=models.TextField(max_length=5000),
        ),
    ]
