# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0005_auto_20180211_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(max_length=160),
        ),
    ]
