# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-15 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bible', '0006_auto_20180214_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book', verbose_name=b'Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'User')),
            ],
            options={
                'db_table': 'bookmark_book',
            },
        ),
    ]
