# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-28 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0007_bookmarkbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='abstract_trempelas',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
